"""One set of planted cases (T-94): the self-test of the intake runs every case before each intake and refuses to
start when a case is no longer found and cleaned (R-004).

Every case carries the invented form of the gate's self-test (tests/fixtures.py lists it as SELFTEST_FORM) or an
invented piece of structured data, in one written shape. `second` marks the cases the second check of the intake
must find on its own; it works on whole words, so a form glued into another word is left to the matcher.
"""
from __future__ import annotations

from awb import register

CODE = "ORG-SELF"
FORM = "Qwxzv Probefirma"
SHORT = "Qwxzv"
ADDED = "2026-09-24"

# (label, text, class the matcher must report, the second check must find it too)
CASES: tuple[tuple[str, str, str, bool], ...] = (
    ("plain", "offer draft for Qwxzv Probefirma, second round", "name", True),
    ("upper case", "OFFER FOR QWXZV PROBEFIRMA TODAY", "name", True),
    ("lower case", "offer for qwxzv probefirma today", "name", True),
    ("hyphen", "the Qwxzv-Probefirma offer", "name", True),
    ("underscore", "file Qwxzv_Probefirma_offer.pptx", "name", True),
    ("dots", "see Qwxzv.Probefirma.offer", "name", True),
    ("glued", "file QwxzvProbefirma offer", "name", True),
    ("glued lower case", "file qwxzvprobefirma offer", "name", True),
    ("line break", "offer for Qwxzv\nProbefirma today", "name", True),
    ("spaced letters", "Q w x z v   P r o b e f i r m a", "name", True),
    ("zero width", "offer for Qwx​zv Probefirma", "name", True),
    ("soft hyphen", "offer for Qwxzv Probe­firma", "name", True),
    ("genitive", "Qwxzv Probefirmas offer", "name", True),
    ("short form", "the Qwxzv team", "name", True),
    ("short form glued", "QWXZVoffer file", "name", False),
    ("look-alike letter", "offer for Qwxzv Prоbefirma", "name", True),
    ("html entity", "offer for Qwxzv&#32;Probefirma", "name", True),
    ("url encoded", "offer%20for%20Qwxzv%20Probefirma", "name", True),
    ("mail address", "write to anna.berg@example.org today", "mail", False),
    ("iban", "IBAN DE89 3704 0044 0532 0130 00", "iban", False),
    ("phone number", "call +49 30 1234567 today", "phone", False),
    # added 2026-09-25: more written shapes of the form and more kinds of structured data, each tried against the
    # engine first; two of them showed gaps that were closed (an IBAN in lower case, a phone number with 00)
    ("title case second word", "offer for Qwxzv probefirma today", "name", True),
    ("mixed case", "offer for qWXZV pROBEFIRMA today", "name", True),
    ("double quotes", "the \"Qwxzv Probefirma\" offer", "name", True),
    ("german quotes", "das Angebot \u201eQwxzv Probefirma\u201c heute", "name", True),
    ("guillemets", "the \u00abQwxzv Probefirma\u00bb offer", "name", True),
    ("parentheses", "the offer (Qwxzv Probefirma) today", "name", True),
    ("brackets", "the offer [Qwxzv Probefirma] today", "name", True),
    ("english possessive", "Qwxzv Probefirma's offer is due", "name", True),
    ("typographic apostrophe", "Qwxzv Probefirma\u2019s offer is due", "name", True),
    ("tab between", "offer for Qwxzv\tProbefirma today", "name", True),
    ("many spaces", "offer for Qwxzv     Probefirma today", "name", True),
    ("no-break space", "offer for Qwxzv\u00a0Probefirma today", "name", True),
    ("narrow no-break space", "offer for Qwxzv\u202fProbefirma today", "name", True),
    ("en space", "offer for Qwxzv\u2002Probefirma today", "name", True),
    ("unicode hyphen", "the Qwxzv\u2010Probefirma offer", "name", True),
    ("non-breaking hyphen", "the Qwxzv\u2011Probefirma offer", "name", True),
    ("en dash between", "the Qwxzv\u2013Probefirma offer", "name", True),
    ("slash between", "the Qwxzv/Probefirma offer", "name", True),
    ("upper glued", "file QWXZVPROBEFIRMA offer", "name", True),
    ("path segment", "stored under /data/qwxzv-probefirma/offer.pdf", "name", True),
    ("url host", "see https://www.qwxzv-probefirma.example/offer", "name", True),
    ("markdown bold", "offer for **Qwxzv Probefirma** today", "name", True),
    ("markdown italic", "offer for _Qwxzv Probefirma_ today", "name", True),
    ("html bold split", "offer for <b>Qwxzv</b> Probefirma today", "name", True),
    ("html inside word", "offer for Qwx<i>zv</i> Probefirma today", "name", False),
    ("nbsp entity", "offer for Qwxzv&nbsp;Probefirma today", "name", True),
    ("hex entity letter", "offer for &#x51;wxzv Probefirma today", "name", True),
    ("form encoded", "q=Qwxzv+Probefirma&x=1", "name", True),
    ("zero width joiner", "offer for Qwx\u200dzv Probefirma", "name", True),
    ("word joiner", "offer for Qwxzv Probe\u2060firma", "name", True),
    ("byte order mark inside", "offer for Qwxzv Pro\ufeffbefirma", "name", True),
    ("accent", "offer for Qwxzv Prob\u00e9firma today", "name", True),
    ("umlaut look-alike", "offer for Qwxzv Pr\u00f6befirma today", "name", True),
    ("cyrillic x", "offer for Qw\u0445zv Probefirma today", "name", False),
    ("greek rho", "offer for Qwxzv \u03a1robefirma today", "name", True),
    ("fullwidth", "offer for \uff31\uff57\uff58\uff5a\uff56 \uff30\uff52\uff4f\uff42\uff45\uff46\uff49\uff52\uff4d\uff41", "name", True),
    ("hyphenated at line end", "offer for Qwxzv Probe-\nfirma today", "name", True),
    ("crlf between", "offer for Qwxzv\r\nProbefirma today", "name", True),
    ("json value", "{\"customer\": \"Qwxzv Probefirma\", \"stage\": 2}", "name", True),
    ("csv field", "Qwxzv Probefirma;offer;2026", "name", True),
    ("table cell", "| Qwxzv Probefirma | offer |", "name", True),
    ("code span", "the key `Qwxzv Probefirma` stays", "name", True),
    ("file name with version", "Qwxzv Probefirma offer v2.pptx", "name", True),
    ("reversed order", "Probefirma Qwxzv met today", "name", True),
    ("short upper", "the QWXZV team", "name", True),
    ("short lower", "the qwxzv team", "name", False),
    ("short possessive", "Qwxzv's team", "name", True),
    ("short hyphen suffix", "the Qwxzv-team met", "name", True),
    ("short hashtag", "see #qwxzv for news", "name", False),
    ("short mention", "ask @qwxzv today", "name", False),
    ("short underscore suffix", "bucket qwxzv_prod is full", "name", False),
    ("short in a sentence end", "The contract is with Qwxzv.", "name", True),
    ("short quoted", "the 'Qwxzv' offer", "name", True),
    ("genitive short", "Qwxzvs Angebot", "name", True),
    ("dative plural", "den Qwxzv Probefirmen", "name", True),
    ("mail upper case", "write to Anna.Berg@Example.org today", "mail", False),
    ("mailto link", "mailto:anna.berg@example.org", "mail", False),
    ("mail at ip literal", "write to anna@[192.0.2.1] today", "mail", False),
    ("mail with plus", "write to anna+offer@example.org today", "mail", False),
    ("iban no spaces", "IBAN DE89370400440532013000 today", "iban", False),
    ("iban lower case", "iban de89 3704 0044 0532 0130 00", "iban", False),
    ("iban uk", "IBAN GB82 WEST 1234 5698 7654 32", "iban", False),
    ("iban netherlands", "IBAN NL91ABNA0417164300", "iban", False),
    ("iban austria", "IBAN AT61 1904 3002 3457 3201", "iban", False),
    ("iban swiss", "IBAN CH93 0076 2011 6238 5295 7", "iban", False),
    ("phone with zero in brackets", "call +49 (0)30 1234567 today", "phone", False),
    ("phone national slash", "call 030/1234567 today", "phone", False),
    ("phone double zero", "call 0049 30 1234567 today", "phone", False),
    ("phone hyphens", "call +49-30-1234567 today", "phone", False),
    ("phone swiss", "call +41 44 123 45 67 today", "phone", False),
    ("phone dutch", "call +31 20 123 4567 today", "phone", False),
    ("phone mobile", "call 0171 1234567 today", "phone", False),
    ("public ipv4", "the host 93.184.216.34 answers", "ip", False),
    ("ipv6", "the host 2a01:4f8:1c1c:1234::1 answers", "ip", False),
    ("mac address", "the port 00:1A:2B:3C:4D:5E is up", "mac", False),
    ("bic", "BIC QWXZDEFF today", "bic", False),
    ("vat id", "VAT DE123456789 today", "vat", False),
    ("register number", "HRB 123456 B Berlin", "hrb", False),
    ("tax number", "Steuernummer 12/345/67890", "tax", False),
    ("domain alone", "see qwxzv-probefirma.de for it", "url", True),
    # added 2026-09-27 after the red team (calibration/redteam-2026-09-27.md): the shapes eight finders got
    # through, each one caught now
    ("entity without semicolon", "offer for &#81wxzv Probefirma today", "name", True),
    ("entity with eight digits", "offer for &#x00000051;wxzv Probefirma today", "name", True),
    ("rtf unicode escape", "offer for Qwxzv \\u80?robefirma today", "name", True),
    ("python hex escape", "offer for \\x51wxzv Probefirma today", "name", True),
    ("terminal colour codes", "offer for \x1b[01;31mQwxzv\x1b[m Probefirma today", "name", True),
    ("quoted printable soft break", "offer for Qwxzv Probe=\nfirma =C3=A4 today", "name", True),
    ("tag with a line break inside", "offer for Qwx<em\nclass=\"x\">zv</em> Probefirma", "name", False),
    ("cdata inside", "offer for Qwx<![CDATA[]]>zv Probefirma", "name", False),
    ("processing instruction inside", "offer for Qwx<?x?>zv Probefirma", "name", False),
    ("long tag inside", "offer for Qwx<span style=\"%s\">zv</span> Probefirma" % ("a" * 300), "name", False),
    ("half glued to digits", "host qwx-zv01 is down", "name", False),
    ("digits glued before a split form", "code 01qwx-zv today", "name", False),
    ("split before a glued word", "| Qwxzv | Probefirmastr |", "name", False),
    ("base64 in short lines", "b2ZmZXIgZm9yIFF3eHp2IFBy\nb2JlZmlybWEsIHNlY29uZCBy\nb3VuZA==", "name", False),
    ("base64 in quoted lines", "> b2ZmZXIgZm9yIFF3eHp2IFBy\n> b2JlZmlybWEsIHNlY29uZCBy\n> b3VuZA==", "name", False),
    ("hex with 0x in front", "blob 0x5177787a762050726f62656669726d612c end", "name", False),
    ("hex with backslash x in front", "blob \\x5177787a762050726f62656669726d612c end", "name", False),
    ("mail at spelled", "write to anna (at) example (dot) org today", "mail", False),
    ("mail bracket at", "write to anna [at] example.org today", "mail", False),
    ("mail quoted local part", "write to \"anna berg\"@example.org today", "mail", False),
    ("mail broken after the at", "write to anna@\nexample.org today", "mail", False),
    ("mail umlaut host", "write to anna@b\u00e4ckerei.example today", "mail", False),
    ("mail ipv6 literal", "write to anna@[IPv6:2001:db8::7] today", "mail", False),
    ("mail markdown escapes", "write to anna\\@example\\.org today", "mail", False),
    ("url defanged", "see mailhost[.]example for it", "url", False),
    ("url hxxp", "see hxxps://www[.]qwxzv-portal[.]shop/x for it", "url", False),
    ("url new tld", "see qwxzv-portal.shop for it", "url", False),
    ("url wildcard host", "the certificate covers *.qwxzv-portal.example", "url", False),
    ("url comment inside", "the host mailhost<!-- x -->.example today", "url", False),
    ("ip zero padded", "host 203.000.113.007 answers", "ip", False),
    ("ip cloud host name", "node ip-203-0-113-7 answers", "ip", False),
    ("ip after ip-nr label", "server IP-Nr. 203.0.113.9 answers", "ip", False),
    ("ip fullwidth digits", "host \uff12\uff10\uff13.\uff10.\uff11\uff11\uff13.\uff19 answers", "ip", False),
    ("ip letter spaced", "host 2 0 3 . 0 . 1 1 3 . 9 answers", "ip", False),
    ("ipv6 label glued", "host ip:2001:db8::7 answers", "ip", False),
    ("mac cisco dotted", "port 001a.2b3c.4d5e is up", "mac", False),
    ("mac label glued", "port mac:00:1a:2b:3c:4d:5e is up", "mac", False),
    ("iban dashes", "IBAN DE89-3704-0044-0532-0130-00", "iban", False),
    ("iban over two lines", "IBAN DE89 3704 0044 0532\n0130 00", "iban", False),
    ("iban letter spaced", "IBAN D E 8 9 3 7 0 4 0 0 4 4 0 5 3 2 0 1 3 0 0 0", "iban", False),
    ("iban markdown bold group", "IBAN DE89 **3704** 0044 0532 0130 00", "iban", False),
    ("iban label glued", "IBANDE89370400440532013000 today", "iban", False),
    ("iban in table cells", "| DE89 | 3704 | 0044 | 0532 | 0130 | 00 |", "iban", False),
    ("bic lower case", "bic qwxzdeff today", "bic", False),
    ("bic code label", "BIC-Code: QWXZDEFF today", "bic", False),
    ("bic in groups", "BIC QWXZ DE FF heute", "bic", False),
    ("vat spaced groups", "USt-IdNr.: DE 123 456 789", "vat", False),
    ("vat dash", "USt-IdNr.: DE-123456789", "vat", False),
    ("vat austria grouped", "UID: ATU 1234 5678", "vat", False),
    ("vat ireland", "vat IE1234567T today", "vat", False),
    ("phone area in parentheses", "call (030) 555 1234 today", "phone", False),
    ("phone dots", "call 030.555.1234 today", "phone", False),
    ("phone pairs", "call 030 12 34 56 78 today", "phone", False),
    ("phone space dash space", "call +49 30 - 5551234 today", "phone", False),
    ("phone double zero spaced", "call 00 49 30 5551234 today", "phone", False),
    ("phone vienna", "call 01 555 1234 today", "phone", False),
    ("phone over two lines", "call 030\n5551234 today", "phone", False),
    ("phone after tel dot", "Tel.030 5551234 today", "phone", False),
    ("phone fullwidth plus", "call \uff0b49 30 5551234 today", "phone", False),
    ("phone trunk zero apart", "call 0 30 / 5 55 12 34 today", "phone", False),
    ("phone two after a slash", "tel/fax 030 5551234/030 5551235 today", "phone", False),
    ("phone letter spaced", "Tel 0 3 0 5 5 5 1 2 3 4 today", "phone", False),
    ("phone in table columns", "| 030 | 5551234 |", "phone", False),
    ("hrb dash", "register HRB-123456 today", "hrb", False),
    ("hrb nr", "HRB Nr. 123456 today", "hrb", False),
    ("hrb lower case", "hrb 123456 today", "hrb", False),
    ("hrb handelsregister", "Handelsregister B 123456 today", "hrb", False),
    ("tax steuer nr spaces", "Steuer-Nr. 12 345 67890", "tax", False),
    ("tax five and five", "Steuernummer 12345/67890", "tax", False),
    ("tax identifikationsnummer", "Steuer-Identifikationsnummer 12345678901", "tax", False),
    ("hex of a phone number", "blob 63616c6c202b34392033302035353531323334206e6f77 end", "phone", False),
    ("spaced hex dump", "dump 51 77 78 7a 76 20 50 72 6f 62 65 66 69 72 6d 61 end", "name", False),
    ("cyrillic omega and izhitsa", "offer for Q\u0461xz\u0475 Probefirma today", "name", False),
    ("two ibans in a row", "AT61 1904 3002 3457 3201 DE89 3704 0044 0532 0130 00", "iban", False),
    ("phone dotted per digit", "Tel 0.3.0.5.5.5.1.2.3.4 today", "phone", False),
    ("phone with two blanks", "call 030  5551234 today", "phone", False),
    ("phone letter spaced wide", "Tel 0   3   0   5   5   5   1   2   3   4 today", "phone", False),
    ("hex dump of five bytes", "h 51 77 78 7a 76, second round", "name", False),
    ("hrb letter spaced", "Handelsregister HR B 1 2 3 4 5 6", "hrb", False),
)


def entries() -> list[register.Entry]:
    """The register of the self-test: the invented form and its short form, nothing else."""
    return [register.Entry(CODE, "ORG", FORM, ADDED, "active"), register.Entry(CODE, "ORG", SHORT, ADDED, "active")]
